##################################################
# file: CurrencyService_client.py
# 
# client stubs generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#     /usr/bin/wsdl2py -b http://www.restfulwebservices.net/wcf/CurrencyService.svc?wsdl
# 
##################################################

from CurrencyService_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
from ZSI.schema import GED, GTD
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class CurrencyServiceLocator:
    BasicHttpBinding_ICurrencyService_address = "http://www.restfulwebservices.net/wcf/CurrencyService.svc"
    def getBasicHttpBinding_ICurrencyServiceAddress(self):
        return CurrencyServiceLocator.BasicHttpBinding_ICurrencyService_address
    def getBasicHttpBinding_ICurrencyService(self, url=None, **kw):
        return BasicHttpBinding_ICurrencyServiceSOAP(url or CurrencyServiceLocator.BasicHttpBinding_ICurrencyService_address, **kw)

# Methods
class BasicHttpBinding_ICurrencyServiceSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: GetConversionRate
    def GetConversionRate(self, request, **kw):
        if isinstance(request, ICurrencyService_GetConversionRate_InputMessage) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="GetConversionRate", **kw)
        # no output wsaction
        response = self.binding.Receive(ICurrencyService_GetConversionRate_OutputMessage.typecode)
        return response

ICurrencyService_GetConversionRate_InputMessage = GED("http://www.restfulwebservices.net/ServiceContracts/2008/01", "GetConversionRate").pyclass

ICurrencyService_GetConversionRate_OutputMessage = GED("http://www.restfulwebservices.net/ServiceContracts/2008/01", "GetConversionRateResponse").pyclass
