##################################################
# file: CurrencyService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py -b http://www.restfulwebservices.net/wcf/CurrencyService.svc?wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from CurrencyService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
ICurrencyService_GetConversionRate_InputMessage = GED("http://www.restfulwebservices.net/ServiceContracts/2008/01", "GetConversionRate").pyclass

ICurrencyService_GetConversionRate_OutputMessage = GED("http://www.restfulwebservices.net/ServiceContracts/2008/01", "GetConversionRateResponse").pyclass


# Service Skeletons
class CurrencyService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/wcf/CurrencyService.svc', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_GetConversionRate(self, ps, **kw):
        request = ps.Parse(ICurrencyService_GetConversionRate_InputMessage.typecode)
        return request,ICurrencyService_GetConversionRate_OutputMessage()

    soapAction['GetConversionRate'] = 'soap_GetConversionRate'
    root[(ICurrencyService_GetConversionRate_InputMessage.typecode.nspname,ICurrencyService_GetConversionRate_InputMessage.typecode.pname)] = 'soap_GetConversionRate'

